[package]
name = "signature_verifier"
version = "0.1.0"
authors = ["Khushraj Rathod <khushraj.rathod@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
binary_macros = "1.0.0"
rsa = "0.4.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.9.3"
