[workspace]

members = [
    "cli",

    "static/types",
    "static/constants",

    "functionality/signature_verifier",
    "functionality/git_updater",
    "functionality/logger",

    "event_handlers/http_event_handler",
    "event_handlers/stdio_event_handler"
]
