[package]
name = "repl_deploy"
version = "0.1.0"
authors = ["Khushraj Rathod <khushraj.rathod@gmail.com>"]
edition = "2018"

[dependencies]
rsa = "0.9.2"
serde_json = "1.0.104"
clap = "2.34.0"
anyhow = "1.0.72"
tokio = { version = "1.31.0", features = ["rt-multi-thread", "macros"]}
warp = "0.3"
serde = { version = "1.0.183", features = ["derive"]  }
regex = "1.9.3"
base64 = "0.21.2"
sha2 = "0.10.7"
log = "0.4.20"
pretty_env_logger = "0.5.0"

[dev-dependencies]
rand = "0.8.5"