name: Prerelease

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./daemon
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache
      uses: Swatinem/rust-cache@v1.4.0
      with: 
        working-directory: ./daemon

    - name: Build
      run: cargo build --release

    - name: Test
      run: cargo test
      
    - name: Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --manifest-path ./daemon/Cargo.toml
        
    - name: Rename
      run: mv target/release/repl_deploy target/release/repl.deploy

    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          daemon/target/release/repl.deploy
