name: Release

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache
      uses: Swatinem/rust-cache@v1.2.0

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --manifest-path ./daemon/rust-impl
    
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ./daemon/rust-impl
      
    - name: Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --manifest-path ./daemon/rust-impl

    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.1.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          target/release/repl-mc
